build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\contao

cache:
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=c:\php;%PATH%

install:
  - mkdir c:\php && cd c:\php
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.1.10-Win32-VC14-x86.zip
  - 7z x php-7.1.10-Win32-VC14-x86.zip -y >nul
  - del *.zip
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_bz2.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_exif.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_mysqli.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_soap.dll >> php.ini
  - echo extension=php_sockets.dll >> php.ini
  - echo extension=php_xmlrpc.dll >> php.ini
  - echo extension=php_xsl.dll >> php.ini
  - cd c:\projects\contao
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - IF %APPVEYOR_REPO_TAG%==true (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_TAG_NAME%) ELSE (SET COMPOSER_ROOT_VERSION=dev-%APPVEYOR_REPO_BRANCH%)
  - php composer.phar update --no-progress --no-interaction --ansi

test_script:
  - cd c:\projects\contao
  - vendor\bin\phpunit.bat
