services:
    contao.adapter.config:
        class: Contao\CoreBundle\Adapter\ConfigAdapter
        public: false

    contao.adapter.dbafs:
        class: Contao\CoreBundle\Adapter\DbafsAdapter
        public: false

    contao.adapter.backend_main:
        class: Contao\CoreBundle\Adapter\BackendMainAdapter
        public: false

    contao.adapter.backend_index:
        class: Contao\CoreBundle\Adapter\BackendIndexAdapter
        public: false

    contao.adapter.backend_install:
        class: Contao\CoreBundle\Adapter\BackendInstallAdapter
        public: false

    contao.adapter.backend_password:
        class: Contao\CoreBundle\Adapter\BackendPasswordAdapter
        public: false

    contao.adapter.backend_preview:
        class: Contao\CoreBundle\Adapter\BackendPreviewAdapter
        public: false

    contao.adapter.backend_confirm:
        class: Contao\CoreBundle\Adapter\BackendConfirmAdapter
        public: false

    contao.adapter.backend_file:
        class: Contao\CoreBundle\Adapter\BackendFileAdapter
        public: false

    contao.adapter.backend_help:
        class: Contao\CoreBundle\Adapter\BackendHelpAdapter
        public: false

    contao.adapter.backend_page:
        class: Contao\CoreBundle\Adapter\BackendPageAdapter
        public: false

    contao.adapter.backend_popup:
        class: Contao\CoreBundle\Adapter\BackendPopupAdapter
        public: false

    contao.adapter.backend_switch:
        class: Contao\CoreBundle\Adapter\BackendSwitchAdapter
        public: false

    contao.adapter.frontend_index:
        class: Contao\CoreBundle\Adapter\FrontendIndexAdapter
        public: false

    contao.adapter.frontend_cron:
        class: Contao\CoreBundle\Adapter\FrontendCronAdapter
        public: false

    contao.adapter.frontend_share:
        class: Contao\CoreBundle\Adapter\FrontendShareAdapter
        public: false

    contao.adapter.frontend:
        class: Contao\CoreBundle\Adapter\FrontendAdapter
        public: false

    contao.adapter.system:
        class: Contao\CoreBundle\Adapter\SystemAdapter
        public: false
