services:
    contao.command.automator:
        class: Contao\CoreBundle\Command\AutomatorCommand
        arguments:
            - "@contao.framework"
        tags:
            -  { name: console.command }
    contao.command.filesync:
        class: Contao\CoreBundle\Command\FilesyncCommand
        arguments:
            - "@contao.framework"
        tags:
            -  { name: console.command }