services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    contao.command.automator:
        class: Contao\CoreBundle\Command\AutomatorCommand

    contao.command.filesync:
        class: Contao\CoreBundle\Command\FilesyncCommand

    contao.command.install:
        class: Contao\CoreBundle\Command\InstallCommand

    contao.command.symlinks:
        class: Contao\CoreBundle\Command\SymlinksCommand

    contao.command.user_password_command:
        class: Contao\CoreBundle\Command\UserPasswordCommand

    contao.command.version:
        class: Contao\CoreBundle\Command\VersionCommand
