services:
    contao.controller.backend:
        class: Contao\CoreBundle\Controller\BackendController
        arguments:
            - "@terminal42.contao.adapter.backend_main"
            - "@terminal42.contao.adapter.backend_index"
            - "@terminal42.contao.adapter.backend_install"
            - "@terminal42.contao.adapter.backend_password"
            - "@terminal42.contao.adapter.backend_preview"
            - "@terminal42.contao.adapter.backend_confirm"
            - "@terminal42.contao.adapter.backend_file"
            - "@terminal42.contao.adapter.backend_help"
            - "@terminal42.contao.adapter.backend_page"
            - "@terminal42.contao.adapter.backend_popup"
            - "@terminal42.contao.adapter.backend_switch"

    contao.controller.frontend:
        class: Contao\CoreBundle\Controller\FrontendController
        arguments:
          - "@terminal42.contao.adapter.frontend_index"
          - "@terminal42.contao.adapter.frontend_cron"
          - "@terminal42.contao.adapter.frontend_share"
