##
# Listener priorities
#
# The priorities of the following listeners must be lower than the one of the
# Symfony route listener (defaults to 32).
#
# - 20: RefererIdListener
# - 20: LocaleListener
#
# The priorities of the following listeners must be lower than the one of the
# Symfony locale listener (defaults to 16).
#
# - 10: InitializeSystemListener
#
# Exception listener
#
# The priority of the exception listeners must be higher than the one of the
# Twig exception listener (defaults to -128). The pretty error screen listener should be
# very late to not interfere with the exception bubbling.
#
# -  96: ExceptionConverterListener
# -  64: ResponseExceptionListener
# - -96: PrettyErrorScreensListener
#
# Maintenance listener
#
# The priority of the maintenance listener must be higher than the one of the
# Lexik maintenance bundle (defaults to 0).
#
# - 10: BypassMaintenanceListener
#
# Do not change the priorities unless you know what you are doing!
##
services:
    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        arguments:
            - "@contao.framework"
            - "%fragment.path%"
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.bypass_maintenance:
        class: Contao\CoreBundle\EventListener\BypassMaintenanceListener
        arguments:
            - "@session"
            - "%contao.security.disable_ip_check%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }

    contao.listener.command_scheduler:
        class: Contao\CoreBundle\EventListener\CommandSchedulerListener
        arguments:
            - "@contao.framework"
            - "@database_connection"
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.doctrine_schema:
        class: Contao\CoreBundle\EventListener\DoctrineSchemaListener
        arguments:
            - "@contao.doctrine.dca_schema_provider"
        tags:
            - { name: doctrine.event_listener, event: onSchemaIndexDefinition }
            - { name: doctrine.event_listener, event: postGenerateSchema }

    contao.listener.exception_converter:
        class: Contao\CoreBundle\EventListener\ExceptionConverterListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 96 }

    contao.listener.insecure_installation:
        class: Contao\CoreBundle\EventListener\InsecureInstallationListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    contao.listener.locale:
        class: Contao\CoreBundle\EventListener\LocaleListener
        factory: [Contao\CoreBundle\EventListener\LocaleListener, createWithLocales]
        arguments:
            - "%kernel.default_locale%"
            - "%kernel.root_dir%"
        calls:
            - ["setContainer", ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }

    contao.listener.merge_http_headers:
        class: Contao\CoreBundle\EventListener\MergeHttpHeadersListener
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 256 }

    contao.listener.pretty_error_screens:
        class: Contao\CoreBundle\EventListener\PrettyErrorScreenListener
        arguments:
            - "%contao.pretty_error_screens%"
            - "@twig"
            - "@contao.framework"
            - "@security.token_storage"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -96 }

    contao.listener.referer_id:
        class: Contao\CoreBundle\EventListener\RefererIdListener
        arguments:
            - "@contao.referer_id.manager"
        calls:
            - ["setContainer", ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }

    contao.listener.response_exception:
        class: Contao\CoreBundle\EventListener\ResponseExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 64 }

    contao.listener.store_referer:
        class: Contao\CoreBundle\EventListener\StoreRefererListener
        arguments:
            - "@session"
            - "@security.token_storage"
            - "@security.authentication.trust_resolver"
        calls:
            - ["setContainer", ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        arguments:
            - "@contao.framework"
        calls:
            - ["setContainer", ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    contao.listener.user_session:
        class: Contao\CoreBundle\EventListener\UserSessionListener
        arguments:
            - "@session"
            - "@database_connection"
            - "@security.token_storage"
            - "@security.authentication.trust_resolver"
        calls:
            - ["setContainer", ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
