contao:
    resource: "@ContaoCoreBundle/Controller"
    type: annotation

# Redirect /contao/ to /contao
contao_backend_redirect:
    path: /contao/
    defaults:
        _scope: backend
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: contao_backend
        permanent: true

contao_frontend:
    resource: .
    type: contao_frontend

contao_root:
    path: /
    defaults:
        _scope: frontend
        _token_check: true
        _controller: Contao\CoreBundle\Controller\FrontendController::indexAction

# The catch all route must be the last one!
contao_catch_all:
    path: /{_url_fragment}
    defaults:
        _scope: frontend
        _token_check: true
        _controller: Contao\CoreBundle\Controller\FrontendController::indexAction
    requirements:
        _url_fragment: .*
