contao:
    resource: "@ContaoCoreBundle/Controller"
    type: annotation

# Caching preflight request
contao_preflight:
    path: /contao/preflight
    defaults:
        _scope: frontend
        _controller: "contao.controller.preflight_request:indexAction"

# Redirect /contao/ to /contao
contao_backend_redirect:
    path: /contao/
    defaults:
        _scope: backend
        _controller: "FrameworkBundle:Redirect:redirect"
        route: contao_backend
        permanent: true

contao_frontend:
    resource: .
    type: contao_frontend

contao_root:
    path: /
    defaults:
        _scope: frontend
        _token_check: true
        _controller: "ContaoCoreBundle:Frontend:index"

# The catch all route must be the last one!
contao_catch_all:
    path: /{_url_fragment}
    defaults:
        _scope: frontend
        _token_check: true
        _controller: "ContaoCoreBundle:Frontend:index"
    requirements:
        _url_fragment: .*
