security:
    providers:
        contao.security.user_provider:
            id: contao.security.user_provider

        contao.security.backend_user_provider:
            id: contao.security.backend_user_provider

    encoders:
        default:
            algorithm: bcrypt

        legacy:
            id: contao.security.legacy_password_encoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        install:
            pattern: ^/contao/install
            security: false

        contao_backend:
            request_matcher: contao.routing.backend_matcher
            provider: contao.security.backend_user_provider
            anonymous: ~
            switch_user: true

            form_login:
                login_path: /contao/login
                check_path: /contao/login
                default_target_path: /contao
                username_parameter: username
                password_parameter: password

            logout:
                path: /contao/logout
                target: /contao/login

        contao_frontend:
            request_matcher: contao.routing.frontend_matcher
            stateless: true
            simple_preauth:
                authenticator: contao.security.authenticator

    access_control:
        - { path: ^/contao/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contao, roles: ROLE_USER }
