contao:
    resource: '@ContaoCoreBundle/src/Controller'
    type: attribute

contao_images:
    resource: .
    type: contao_images

# Redirect /contao/ to /contao
contao_backend_redirect:
    path: '%contao.backend.route_prefix%/'
    defaults:
        _scope: backend
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: contao_backend
        permanent: true

contao_backend_fallback:
    path: '%contao.backend.route_prefix%/{parameters}'
    defaults:
        _scope: backend
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: '@ContaoCore\Error\backend.html.twig'
        context:
            template: '@ContaoCore\Error\backend.html.twig'
            language: en
            statusName: Page Not Found
            exception: The requested page does not exist.
        statusCode: 404
    requirements:
        parameters: .*
