services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [setContainer, ['@Psr\Container\ContainerInterface']]

    Contao\CoreBundle\Controller\BackendTemplateStudioController:
        arguments:
            - '@contao.twig.filesystem_loader'
            - '@contao.twig.finder_factory'
